import { GitHubAPI } from './api';

export interface ReadmeStats {
    totalSolved: number;
    streak: number;
    platforms: Record<string, number>;
    difficulties: Record<string, number>;
    languages: Record<string, number>;
    recentSubmissions: Array<{ platform: string, name: string, date: string }>;
}

export class ReadmeGenerator {
    private api: GitHubAPI;
    private owner: string;
    private repo: string;

    constructor(token: string, owner: string, repo: string) {
        this.api = new GitHubAPI(token);
        this.owner = owner;
        this.repo = repo;
    }

    private generateMarkdown(stats: ReadmeStats): string {
        return `# CodeSync Repository 🚀

This repository is automatically synchronized using [CodeSync](https://github.com/ASingh2425/code_extension).

## 📊 Statistics

- **Total Problems Solved:** ${stats.totalSolved}
- **Current Streak:** ${stats.streak} days

### Platforms
${Object.entries(stats.platforms).map(([platform, count]) => `- **${platform}:** ${count}`).join('\n')}

### Difficulty Distribution
${Object.entries(stats.difficulties).map(([diff, count]) => `- **${diff}:** ${count}`).join('\n')}

### Languages Used
${Object.entries(stats.languages).map(([lang, count]) => `- **${lang}:** ${count}`).join('\n')}

## 🕒 Recent Submissions
${stats.recentSubmissions.map(sub => `- **${sub.platform}**: ${sub.name} (${new Date(sub.date).toLocaleDateString()})`).join('\n')}

---
*Auto-generated by CodeSync.*
`;
    }

    async updateReadme(stats: ReadmeStats) {
        try {
            const markdown = this.generateMarkdown(stats);
            const baseSha = await this.api.getBranchSha(this.owner, this.repo, 'main');
            
            // Get base tree
            const commitData = await this.api.request(`/repos/${this.owner}/${this.repo}/git/commits/${baseSha}`);
            const baseTreeSha = commitData.tree.sha;

            // Create blob for README
            const blob = await this.api.createBlob(this.owner, this.repo, markdown);

            // Update tree
            const newTree = await this.api.createTree(this.owner, this.repo, baseTreeSha, [
                { path: 'README.md', mode: '100644', type: 'blob', sha: blob.sha }
            ]);

            // Create commit
            const newCommit = await this.api.createCommit(this.owner, this.repo, 'Update README.md with latest stats', newTree.sha, baseSha);

            // Update ref
            await this.api.updateRef(this.owner, this.repo, 'main', newCommit.sha);
            
            console.log('README.md updated successfully!');
        } catch (error) {
            console.error('Failed to update README.md:', error);
            throw error;
        }
    }
}
